[book]
authors = ["yukinarit"]
language = "en"
multilingual = true
src = "docs"
title = "pyserde documentation"

[output.html]
git-repository-url = "https://github.com/yukinarit/pyserde"
edit-url-template = "https://github.com/yukinarit/pyserde/edit/main/{path}"
