[book]
authors = ["yukinarit"]
language = "ja"
src = "./"
title = "pyserde documentation"

[output.html]
git-repository-url = "https://github.com/yukinarit/pyserde"
edit-url-template = "https://github.com/yukinarit/pyserde/edit/main/docs/ja/{path}"
